server:
  port: 8080

efs:
  base-path: /mnt/efs/tickets

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${AWS_S3_BUCKET:tickets-eventos-tu-grupo}
    endpoint: ${AWS_S3_ENDPOINT:}
    path-style: true

spring:
  datasource:
    url: jdbc:h2:mem:ticketsdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/3e23a328-3849-428a-91b6-2e47dcc18093/

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

app:
  queues:
    ok: tickets.ok
    error: tickets.error

management:
  endpoints:
    web:
      exposure:
        include: health,info
